### ISSUE TITLE
Exception if input box is rejected (Escape klicked)

### ISSUE THREAD

**Issue by SrTobi** [SrTobi/code-bing#9]
```
TypeError: Cannot read property 'split' of undefined
    at getSearchUrl (\code-bing\out\src\extension.js:55:27)
    at searchFor (\code-bing\out\src\extension.js:93:10)
    at Object.p [as _notify] (\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:3663)
    at Object.__dirname.undefined.L.enter (\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:6825)
    at __dirname.undefined.t.Class.define._run (\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:8651)
    at __dirname.undefined.t.Class.define._completed (\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:5:8092)
    at Object.p.handle (\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:11:17220)
    at process.<anonymous> (\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:19:9111)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
```

**Comment by jahands** [comment]
Fixed in #5
